services:
  lgbt-telegram-bot:
    build: .
    restart: unless-stopped
    user: "100000:100000"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - bot-data:/usr/src/app/data
    deploy:
      resources:
        limits:
          cpus: 0.8
          memory: 400M

volumes:
  bot-data:
