services:
  lgbt-telegram-bot:
    build: .
    restart: unless-stopped
    volumes:
      - bot-data:/usr/src/app/data
    deploy:
      resources:
        limits:
          cpus: 0.8
          memory: 400M

volumes:
  bot-data:
