services:
  lgbt-telegram-bot:
    build: .
    restart: unless-stopped
    volumes:
      - lgbt-telegram-bot:/usr/src/app
    deploy:
      resources:
        limits:
          cpus: 0.8
          memory: 400M

volumes:
  lgbt-telegram-bot:
