import { CountryISOCodes } from "../types/bot-types";

export const countryISOCodes: CountryISOCodes = {
    // Latin America
    "ARG": { country: "Argentina", flag: "🇦🇷" },
    "BOL": { country: "Bolivia", flag: "🇧🇴" },
    "BRA": { country: "Brasil", flag: "🇧🇷" },
    "CHL": { country: "Chile", flag: "🇨🇱" },
    "COL": { country: "Colombia", flag: "🇨🇴" },
    "CRI": { country: "Costa Rica", flag: "🇨🇷" },
    "CUB": { country: "Cuba", flag: "🇨🇺" },
    "DOM": { country: "República Dominicana", flag: "🇩🇴" },
    "ECU": { country: "Ecuador", flag: "🇪🇨" },
    "SLV": { country: "El Salvador", flag: "🇸🇻" },
    "GTM": { country: "Guatemala", flag: "🇬🇹" },
    "HTI": { country: "Haití", flag: "🇭🇹" },
    "HND": { country: "Honduras", flag: "🇭🇳" },
    "MEX": { country: "México", flag: "🇲🇽" },
    "NIC": { country: "Nicaragua", flag: "🇳🇮" },
    "PAN": { country: "Panamá", flag: "🇵🇦" },
    "PRY": { country: "Paraguay", flag: "🇵🇾" },
    "PER": { country: "Perú", flag: "🇵🇪" },
    "URY": { country: "Uruguay", flag: "🇺🇾" },
    "VEN": { country: "Venezuela", flag: "🇻🇪" },

    // Europe
    "ALB": { country: "Albania", flag: "🇦🇱" },
    "AND": { country: "Andorra", flag: "🇦🇩" },
    "AUT": { country: "Austria", flag: "🇦🇹" },
    "BLR": { country: "Bielorrusia", flag: "🇧🇾" },
    "BEL": { country: "Bélgica", flag: "🇧🇪" },
    "BIH": { country: "Bosnia y Herzegovina", flag: "🇧🇦" },
    "BGR": { country: "Bulgaria", flag: "🇧🇬" },
    "HRV": { country: "Croacia", flag: "🇭🇷" },
    "CYP": { country: "Chipre", flag: "🇨🇾" },
    "CZE": { country: "Chequia", flag: "🇨🇿" },
    "DNK": { country: "Dinamarca", flag: "🇩🇰" },
    "EST": { country: "Estonia", flag: "🇪🇪" },
    "FIN": { country: "Finlandia", flag: "🇫🇮" },
    "FRA": { country: "Francia", flag: "🇫🇷" },
    "DEU": { country: "Alemania", flag: "🇩🇪" },
    "GRC": { country: "Grecia", flag: "🇬🇷" },
    "HUN": { country: "Hungría", flag: "🇭🇺" },
    "ISL": { country: "Islandia", flag: "🇮🇸" },
    "IRL": { country: "Irlanda", flag: "🇮🇪" },
    "ITA": { country: "Italia", flag: "🇮🇹" },
    "XKX": { country: "Kosovo", flag: "🇽🇰" },
    "LVA": { country: "Letonia", flag: "🇱🇻" },
    "LIE": { country: "Liechtenstein", flag: "🇱🇮" },
    "LTU": { country: "Lituania", flag: "🇱🇹" },
    "LUX": { country: "Luxemburgo", flag: "🇱🇺" },
    "MLT": { country: "Malta", flag: "🇲🇹" },
    "MDA": { country: "Moldavia", flag: "🇲🇩" },
    "MCO": { country: "Mónaco", flag: "🇲🇨" },
    "MNE": { country: "Montenegro", flag: "🇲🇪" },
    "NLD": { country: "Países Bajos", flag: "🇳🇱" },
    "MKD": { country: "Macedonia del Norte", flag: "🇲🇰" },
    "NOR": { country: "Noruega", flag: "🇳🇴" },
    "POL": { country: "Polonia", flag: "🇵🇱" },
    "PRT": { country: "Portugal", flag: "🇵🇹" },
    "ROU": { country: "Rumanía", flag: "🇷🇴" },
    "RUS": { country: "Rusia", flag: "🇷🇺" },
    "SMR": { country: "San Marino", flag: "🇸🇲" },
    "SRB": { country: "Serbia", flag: "🇷🇸" },
    "SVK": { country: "Eslovaquia", flag: "🇸🇰" },
    "SVN": { country: "Eslovenia", flag: "🇸🇮" },
    "ESP": { country: "España", flag: "🇪🇸" },
    "SWE": { country: "Suecia", flag: "🇸🇪" },
    "CHE": { country: "Suiza", flag: "🇨🇭" },
    "UKR": { country: "Ucrania", flag: "🇺🇦" },
    "GBR": { country: "Reino Unido", flag: "🇬🇧" },
    "VAT": { country: "Ciudad del Vaticano", flag: "🇻🇦" }
};