export const countryISOCodes: { [key: string]: string } = {
    // Latin America
    "ARG": "Argentina",
    "BOL": "Bolivia",
    "BRA": "Brasil",
    "CHL": "Chile",
    "COL": "Colombia",
    "CRI": "Costa Rica",
    "CUB": "Cuba",
    "DOM": "República Dominicana",
    "ECU": "Ecuador",
    "SLV": "El Salvador",
    "GTM": "Guatemala",
    "HTI": "Haití",
    "HND": "Honduras",
    "MEX": "México",
    "NIC": "Nicaragua",
    "PAN": "Panamá",
    "PRY": "Paraguay",
    "PER": "Perú",
    "URY": "Uruguay",
    "VEN": "Venezuela",

    // Europe
    "ALB": "Albania",
    "AND": "Andorra",
    "AUT": "Austria",
    "BLR": "Bielorrusia",
    "BEL": "Bélgica",
    "BIH": "Bosnia y Herzegovina",
    "BGR": "Bulgaria",
    "HRV": "Croacia",
    "CYP": "Chipre",
    "CZE": "Chequia",
    "DNK": "Dinamarca",
    "EST": "Estonia",
    "FIN": "Finlandia",
    "FRA": "Francia",
    "DEU": "Alemania",
    "GRC": "Grecia",
    "HUN": "Hungría",
    "ISL": "Islandia",
    "IRL": "Irlanda",
    "ITA": "Italia",
    "XKX": "Kosovo",
    "LVA": "Letonia",
    "LIE": "Liechtenstein",
    "LTU": "Lituania",
    "LUX": "Luxemburgo",
    "MLT": "Malta",
    "MDA": "Moldavia",
    "MCO": "Mónaco",
    "MNE": "Montenegro",
    "NLD": "Países Bajos",
    "MKD": "Macedonia del Norte",
    "NOR": "Noruega",
    "POL": "Polonia",
    "PRT": "Portugal",
    "ROU": "Rumanía",
    "RUS": "Rusia",
    "SMR": "San Marino",
    "SRB": "Serbia",
    "SVK": "Eslovaquia",
    "SVN": "Eslovenia",
    "ESP": "España",
    "SWE": "Suecia",
    "CHE": "Suiza",
    "UKR": "Ucrania",
    "GBR": "Reino Unido",
    "VAT": "Ciudad del Vaticano"
};
