import { CountryISOCodes } from "../types/bot-types";

export const countryISOCodes: CountryISOCodes = {
    // Latin America & Caribbean
    "ARG": { country: "Argentina", flag: "🇦🇷" },
    "ATG": { country: "Antigua y Barbuda", flag: "🇦🇬" },
    "BHS": { country: "Bahamas", flag: "🇧🇸" },
    "BRB": { country: "Barbados", flag: "🇧🇧" },
    "BLZ": { country: "Belice", flag: "🇧🇿" },
    "BOL": { country: "Bolivia", flag: "🇧🇴" },
    "BRA": { country: "Brasil", flag: "🇧🇷" },
    "CHL": { country: "Chile", flag: "🇨🇱" },
    "COL": { country: "Colombia", flag: "🇨🇴" },
    "CRI": { country: "Costa Rica", flag: "🇨🇷" },
    "CUB": { country: "Cuba", flag: "🇨🇺" },
    "DMA": { country: "Dominica", flag: "🇩🇲" },
    "DOM": { country: "República Dominicana", flag: "🇩🇴" },
    "ECU": { country: "Ecuador", flag: "🇪🇨" },
    "GRD": { country: "Granada", flag: "🇬🇩" },
    "GTY": { country: "Guyana", flag: "🇬🇾" },
    "GUA": { country: "Guatemala", flag: "🇬🇹" },
    "HTI": { country: "Haití", flag: "🇭🇹" },
    "HND": { country: "Honduras", flag: "🇭🇳" },
    "JAM": { country: "Jamaica", flag: "🇯🇲" },
    "MEX": { country: "México", flag: "🇲🇽" },
    "NIC": { country: "Nicaragua", flag: "🇳🇮" },
    "PAN": { country: "Panamá", flag: "🇵🇦" },
    "PRY": { country: "Paraguay", flag: "🇵🇾" },
    "PER": { country: "Perú", flag: "🇵🇪" },
    "PRI": { country: "Puerto Rico", flag: "🇵🇷" },
    "KNA": { country: "San Cristóbal y Nieves", flag: "🇰🇳" },
    "LCA": { country: "Santa Lucía", flag: "🇱🇨" },
    "VCT": { country: "San Vicente y las Granadinas", flag: "🇻🇨" },
    "SUR": { country: "Surinam", flag: "🇸🇷" },
    "TTO": { country: "Trinidad y Tobago", flag: "🇹🇹" },
    "SLV": { country: "El Salvador", flag: "🇸🇻" },
    "URY": { country: "Uruguay", flag: "🇺🇾" },
    "VEN": { country: "Venezuela", flag: "🇻🇪" },

    // North America
    "CAN": { country: "Canadá", flag: "🇨🇦" },
    "USA": { country: "Estados Unidos", flag: "🇺🇸" },

    // Europe
    "ALB": { country: "Albania", flag: "🇦🇱" },
    "AND": { country: "Andorra", flag: "🇦🇩" },
    "AUT": { country: "Austria", flag: "🇦🇹" },
    "BEL": { country: "Bélgica", flag: "🇧🇪" },
    "BGR": { country: "Bulgaria", flag: "🇧🇬" },
    "BIH": { country: "Bosnia y Herzegovina", flag: "🇧🇦" },
    "BLR": { country: "Bielorrusia", flag: "🇧🇾" },
    "CHE": { country: "Suiza", flag: "🇨🇭" },
    "CYP": { country: "Chipre", flag: "🇨🇾" },
    "CZE": { country: "Chequia", flag: "🇨🇿" },
    "DEU": { country: "Alemania", flag: "🇩🇪" },
    "DNK": { country: "Dinamarca", flag: "🇩🇰" },
    "ESP": { country: "España", flag: "🇪🇸" },
    "EST": { country: "Estonia", flag: "🇪🇪" },
    "FIN": { country: "Finlandia", flag: "🇫🇮" },
    "FRA": { country: "Francia", flag: "🇫🇷" },
    "GBR": { country: "Reino Unido", flag: "🇬🇧" },
    "GRC": { country: "Grecia", flag: "🇬🇷" },
    "HRV": { country: "Croacia", flag: "🇭🇷" },
    "HUN": { country: "Hungría", flag: "🇭🇺" },
    "IRL": { country: "Irlanda", flag: "🇮🇪" },
    "ISL": { country: "Islandia", flag: "🇮🇸" },
    "ITA": { country: "Italia", flag: "🇮🇹" },
    "LIE": { country: "Liechtenstein", flag: "🇱🇮" },
    "LTU": { country: "Lituania", flag: "🇱🇹" },
    "LUX": { country: "Luxemburgo", flag: "🇱🇺" },
    "LVA": { country: "Letonia", flag: "🇱🇻" },
    "MCO": { country: "Mónaco", flag: "🇲🇨" },
    "MDA": { country: "Moldavia", flag: "🇲🇩" },
    "MKD": { country: "Macedonia del Norte", flag: "🇲🇰" },
    "MLT": { country: "Malta", flag: "🇲🇹" },
    "MNE": { country: "Montenegro", flag: "🇲🇪" },
    "NLD": { country: "Países Bajos", flag: "🇳🇱" },
    "NOR": { country: "Noruega", flag: "🇳🇴" },
    "POL": { country: "Polonia", flag: "🇵🇱" },
    "PRT": { country: "Portugal", flag: "🇵🇹" },
    "ROU": { country: "Rumanía", flag: "🇷🇴" },
    "RUS": { country: "Rusia", flag: "🇷🇺" },
    "SMR": { country: "San Marino", flag: "🇸🇲" },
    "SRB": { country: "Serbia", flag: "🇷🇸" },
    "SVK": { country: "Eslovaquia", flag: "🇸🇰" },
    "SVN": { country: "Eslovenia", flag: "🇸🇮" },
    "SWE": { country: "Suecia", flag: "🇸🇪" },
    "UKR": { country: "Ucrania", flag: "🇺🇦" },
    "VAT": { country: "Ciudad del Vaticano", flag: "🇻🇦" },
    "XKX": { country: "Kosovo", flag: "🇽🇰" },

    // Asia & Middle East
    "AFG": { country: "Afganistán", flag: "🇦🇫" },
    "ARM": { country: "Armenia", flag: "🇦🇲" },
    "AZE": { country: "Azerbaiyán", flag: "🇦🇿" },
    "BGD": { country: "Bangladés", flag: "🇧🇩" },
    "BHR": { country: "Baréin", flag: "🇧🇭" },
    "BRN": { country: "Brunéi", flag: "🇧🇳" },
    "BTN": { country: "Bután", flag: "🇧🇹" },
    "CHN": { country: "China", flag: "🇨🇳" },
    "GEO": { country: "Georgia", flag: "🇬🇪" },
    "IDN": { country: "Indonesia", flag: "🇮🇩" },
    "IND": { country: "India", flag: "🇮🇳" },
    "ISR": { country: "Israel", flag: "🇮🇱" },
    "JOR": { country: "Jordania", flag: "🇯🇴" },
    "JPN": { country: "Japón", flag: "🇯🇵" },
    "KAZ": { country: "Kazajistán", flag: "🇰🇿" },
    "KGZ": { country: "Kirguistán", flag: "🇰🇬" },
    "KHM": { country: "Camboya", flag: "🇰🇭" },
    "KOR": { country: "Corea del Sur", flag: "🇰🇷" },
    "KWT": { country: "Kuwait", flag: "🇰🇼" },
    "LAO": { country: "Laos", flag: "🇱🇦" },
    "LBN": { country: "Líbano", flag: "🇱🇧" },
    "LKA": { country: "Sri Lanka", flag: "🇱🇰" },
    "MDV": { country: "Maldivas", flag: "🇲🇻" },
    "MMR": { country: "Myanmar", flag: "🇲🇲" },
    "MNG": { country: "Mongolia", flag: "🇲🇳" },
    "MYS": { country: "Malasia", flag: "🇲🇾" },
    "NPL": { country: "Nepal", flag: "🇳🇵" },
    "OMN": { country: "Omán", flag: "🇴🇲" },
    "PAK": { country: "Pakistán", flag: "🇵🇰" },
    "PHL": { country: "Filipinas", flag: "🇵🇭" },
    "PRK": { country: "Corea del Norte", flag: "🇰🇵" },
    "PSE": { country: "Palestina", flag: "🇵🇸" },
    "QAT": { country: "Catar", flag: "🇶🇦" },
    "SAU": { country: "Arabia Saudita", flag: "🇸🇦" },
    "SGP": { country: "Singapur", flag: "🇸🇬" },
    "SYR": { country: "Siria", flag: "🇸🇾" },
    "THA": { country: "Tailandia", flag: "🇹🇭" },
    "TJK": { country: "Tayikistán", flag: "🇹🇯" },
    "TKM": { country: "Turkmenistán", flag: "🇹🇲" },
    "TLS": { country: "Timor Oriental", flag: "🇹🇱" },
    "TUR": { country: "Turquía", flag: "🇹🇷" },
    "TWN": { country: "Taiwán", flag: "🇹🇼" },
    "ARE": { country: "Emiratos Árabes Unidos", flag: "🇦🇪" },
    "UZB": { country: "Uzbekistán", flag: "🇺🇿" },
    "VNM": { country: "Vietnam", flag: "🇻🇳" },
    "YEM": { country: "Yemen", flag: "🇾🇪" },

    // Africa
    "AGO": { country: "Angola", flag: "🇦🇴" },
    "BDI": { country: "Burundi", flag: "🇧🇮" },
    "BEN": { country: "Benín", flag: "🇧🇯" },
    "BFA": { country: "Burkina Faso", flag: "🇧🇫" },
    "BWA": { country: "Botsuana", flag: "🇧🇼" },
    "CAF": { country: "República Centroafricana", flag: "🇨🇫" },
    "CIV": { country: "Costa de Marfil", flag: "🇨🇮" },
    "CMR": { country: "Camerún", flag: "🇨🇲" },
    "COD": { country: "República Democrática del Congo", flag: "🇨🇩" },
    "COG": { country: "República del Congo", flag: "🇨🇬" },
    "COM": { country: "Comoras", flag: "🇰🇲" },
    "CPV": { country: "Cabo Verde", flag: "🇨🇻" },
    "DJI": { country: "Yibuti", flag: "🇩🇯" },
    "DZA": { country: "Argelia", flag: "🇩🇿" },
    "EGY": { country: "Egipto", flag: "🇪🇬" },
    "ERI": { country: "Eritrea", flag: "🇪🇷" },
    "ETH": { country: "Etiopía", flag: "🇪🇹" },
    "GAB": { country: "Gabón", flag: "🇬🇦" },
    "GHA": { country: "Ghana", flag: "🇬🇭" },
    "GIN": { country: "Guinea", flag: "🇬🇳" },
    "GMB": { country: "Gambia", flag: "🇬🇲" },
    "GNB": { country: "Guinea-Bisáu", flag: "🇬🇼" },
    "GNQ": { country: "Guinea Ecuatorial", flag: "🇬🇶" },
    "KEN": { country: "Kenia", flag: "🇰🇪" },
    "LBR": { country: "Liberia", flag: "🇱🇷" },
    "LBY": { country: "Libia", flag: "🇱🇾" },
    "LSO": { country: "Lesoto", flag: "🇱🇸" },
    "MAR": { country: "Marruecos", flag: "🇲🇦" },
    "MDG": { country: "Madagascar", flag: "🇲🇬" },
    "MLI": { country: "Mali", flag: "🇲🇱" },
    "MOZ": { country: "Mozambique", flag: "🇲🇿" },
    "MRT": { country: "Mauritania", flag: "🇲🇷" },
    "MUS": { country: "Mauricio", flag: "🇲🇺" },
    "MWI": { country: "Malaui", flag: "🇲🇼" },
    "NAM": { country: "Namibia", flag: "🇳🇦" },
    "NER": { country: "Níger", flag: "🇳🇪" },
    "NGA": { country: "Nigeria", flag: "🇳🇬" },
    "RWA": { country: "Ruanda", flag: "🇷🇼" },
    "SDN": { country: "Sudán", flag: "🇸🇩" },
    "SEN": { country: "Senegal", flag: "🇸🇳" },
    "SLE": { country: "Sierra Leona", flag: "🇸🇱" },
    "SOM": { country: "Somalia", flag: "🇸🇴" },
    "SSD": { country: "Sudán del Sur", flag: "🇸🇸" },
    "STP": { country: "Santo Tomé y Príncipe", flag: "🇸🇹" },
    "SWZ": { country: "Esuatini", flag: "🇸🇿" },
    "SYC": { country: "Seychelles", flag: "🇸🇨" },
    "TCD": { country: "Chad", flag: "🇹🇩" },
    "TGO": { country: "Togo", flag: "🇹🇬" },
    "TUN": { country: "Túnez", flag: "🇹🇳" },
    "TZA": { country: "Tanzania", flag: "🇹🇿" },
    "UGA": { country: "Uganda", flag: "🇺🇬" },
    "ZAF": { country: "Sudáfrica", flag: "🇿🇦" },
    "ZMB": { country: "Zambia", flag: "🇿🇲" },
    "ZWE": { country: "Zimbabue", flag: "🇿🇼" },

    // Oceania
    "AUS": { country: "Australia", flag: "🇦🇺" },
    "FJI": { country: "Fiyi", flag: "🇫🇯" },
    "FSM": { country: "Micronesia", flag: "🇫🇲" },
    "KIR": { country: "Kiribati", flag: "🇰🇮" },
    "MHL": { country: "Islas Marshall", flag: "🇲🇭" },
    "NRU": { country: "Nauru", flag: "🇳🇷" },
    "NZL": { country: "Nueva Zelanda", flag: "🇳🇿" },
    "PLW": { country: "Palaos", flag: "🇵🇼" },
    "PNG": { country: "Papúa Nueva Guinea", flag: "🇵🇬" },
    "WSM": { country: "Samoa", flag: "🇼🇸" },
    "SLB": { country: "Islas Salomón", flag: "🇸🇧" },
    "TON": { country: "Tonga", flag: "🇹🇴" },
    "TUV": { country: "Tuvalu", flag: "🇹🇻" },
    "VUT": { country: "Vanuatu", flag: "🇻🇺" }
};